// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: echo.proto

package com.instructure.soseedy;

public final class EchoOuterClass {
  private EchoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_echo_EchoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_echo_EchoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_echo_EchoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_echo_EchoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\necho.proto\022\004echo\"\033\n\013EchoRequest\022\014\n\004tex" +
      "t\030\001 \001(\t\"\034\n\014EchoResponse\022\014\n\004text\030\001 \001(\t2\330\001" +
      "\n\004Echo\022.\n\003Get\022\021.echo.EchoRequest\032\022.echo." +
      "EchoResponse\"\000\0223\n\006Expand\022\021.echo.EchoRequ" +
      "est\032\022.echo.EchoResponse\"\0000\001\0224\n\007Collect\022\021" +
      ".echo.EchoRequest\032\022.echo.EchoResponse\"\000(" +
      "\001\0225\n\006Update\022\021.echo.EchoRequest\032\022.echo.Ec" +
      "hoResponse\"\000(\0010\001B\033\n\027com.instructure.sose" +
      "edyP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_echo_EchoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_echo_EchoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_echo_EchoRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_echo_EchoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_echo_EchoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_echo_EchoResponse_descriptor,
        new java.lang.String[] { "Text", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
