// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: echo.proto

package com.instructure.soseedy;

public final class EchoOuterClass {
  private EchoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
