// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: echo.proto

package com.instructure.soseedy;

public interface EchoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:echo.EchoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The text of a message to be echoed.
   * </pre>
   *
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <pre>
   * The text of a message to be echoed.
   * </pre>
   *
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
