apiVersion: v1
kind: Service
metadata:
  name: esp-grpc-termination
spec:
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http2
  selector:
    app: esp-grpc-termination
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esp-grpc-termination
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: esp-grpc-termination
    spec:
      volumes:
      - name: nginx-ssl
        secret:
          secretName: nginx-ssl
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--ssl_port=9000",
          "--tls_mutual_auth",
          "--service=echo.endpoints.delta-essence-114723.cloud.goog",
          "--rollout_strategy=managed",
          "--backend=grpc://127.0.0.1:50051"
        ]
        ports:
          - containerPort: 9000
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: nginx-ssl
          readOnly: true
      - name: termination
        image: gcr.io/delta-essence-114723/ssl_termination:latest
        ports:
          - containerPort: 50051
