source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'JavaAuth' do
  use_frameworks!

  pod 'SwiftGRPC', git: 'https://github.com/n8armstrong/grpc-swift.git', branch: 'tls-mutual-auth'
end

target 'JavaAuthTests' do
  use_frameworks!

  pod 'SwiftGRPC', git: 'https://github.com/n8armstrong/grpc-swift.git', branch: 'tls-mutual-auth'
end
