apiVersion: v1
kind: Service
metadata:
  name: esp-grpc-passthrough
spec:
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http2
  selector:
    app: esp-grpc-passthrough
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esp-grpc-passthrough
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: esp-grpc-passthrough
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http2_port=9000",
          "--service=echo.endpoints.delta-essence-114723.cloud.goog",
          "--rollout_strategy=managed",
          "--backend=grpc://127.0.0.1:50051"
        ]
        ports:
          - containerPort: 9000
      - name: passthrough
        image: gcr.io/delta-essence-114723/ssl_passthrough:latest
        ports:
          - containerPort: 50051
